@theme earth {
  palette.primary: orange
  semantic.surface: "#F5F0EB"
  semantic.surface-raised: "#FDFAF7"
  semantic.surface-hover: "#EDE5DB"
  semantic.surface-unread: "#F8F3ED"
  semantic.background: "#FAF7F4"
  semantic.border: "#D5C8B8"
  semantic.border-strong: "#B09E8A"
  semantic.text-primary: "#2C2418"
  semantic.text-secondary: "#5E4E3C"
  semantic.text-tertiary: "#8B7A66"
  semantic.text-disabled: "#C4B8A8"
  semantic.text-muted: "#73624E"
  semantic.text-strong: "#1A1510"
  semantic.interactive: "#B45309"
  semantic.interactive-hover: "#92400E"
  semantic.interactive-active: "#78350F"
  semantic.focus-ring: "#DDA66C"
  semantic.info-bg: "#F7F0E7"
  semantic.destructive: "#C0392B"
  semantic.destructive-hover: "#A33224"
  semantic.error: "#C0392B"
  semantic.error-bg: "#FAEDEB"
  semantic.success: "#5F7A2E"
  semantic.success-light: "#F0F4E8"
  semantic.success-muted: "#D4E0B8"
  semantic.success-text: "#3D5020"
  semantic.success-mid: "#4E6626"
  semantic.warning: "#C27C0E"
  semantic.warning-light: "#FBF4E4"
  semantic.warning-muted: "#F0DDB0"
  semantic.warning-text: "#7A4E08"
  semantic.on-interactive: "#FDFAF7"
  semantic.on-destructive: "#FDFAF7"
  semantic.focus-ring-shadow: "rgba(180,83,9,.12)"
  // Severity
  severity.info-bg: "#F7F0E7"
  severity.info-color: "#78350F"
  severity.info-border: "#DDA66C"
  severity.success-bg: "#F0F4E8"
  severity.success-color: "#3D5020"
  severity.success-border: "#B0C878"
  severity.warning-bg: "#FBF4E4"
  severity.warning-color: "#7A4E08"
  severity.warning-border: "#DDB86C"
  severity.error-bg: "#FAEDEB"
  severity.error-color: "#8A2820"
  severity.error-border: "#D89890"

  font.body: "'Merriweather Sans', 'Georgia', serif"
  font.heading: "'Merriweather Sans', 'Georgia', serif"

  radius.sm: "6px"
  radius.md: "8px"
  radius.lg: "12px"

  borders.default: "1px solid #D5C8B8"
  borders.strong: "1px solid #B09E8A"

  elevation.raised: "0 1px 3px rgba(44,36,24,0.08), 0 1px 2px rgba(44,36,24,0.06)"
  elevation.layered: "0 4px 6px rgba(44,36,24,0.08), 0 2px 4px rgba(44,36,24,0.06)"
  elevation.floating: "0 10px 25px rgba(44,36,24,0.1), 0 4px 10px rgba(44,36,24,0.05)"
  elevation.overlay: "0 8px 32px rgba(44,36,24,0.12)"

  // Component tokens
  btn-radius: "8px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FDFAF7"
  btn-secondary-color: "#B45309"
  btn-secondary-border: "#D5C8B8"
  btn-secondary-hover: "#F5F0EB"
  btn-ghost-color: "#73624E"
  btn-ghost-hover: "#EDE5DB"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FDFAF7"
  input-border: "#D5C8B8"
  input-color: "#2C2418"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "8px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FDFAF7"
  select-border: "#D5C8B8"
  select-radius: "8px"
  modal-radius: "12px"
  modal-shadow: "0 20px 60px rgba(44,36,24,.12)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#B09E8A"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#D5C8B8"
  // Alert — Earth
  alert-radius: "8px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "semantic.destructive"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Earth organic tones
  gradient.stat-primary: "linear-gradient(135deg, #F7F0E7, #DDA66C)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F7F0E7, #E8D4B8)"
  gradient.stat-success: "linear-gradient(135deg, #F0F4E8, #D4E0B8)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #F0F4E8, #E2EAD0)"
  gradient.stat-warning: "linear-gradient(135deg, #FBF4E4, #F0DDB0)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FBF4E4, #F5E8CA)"
  gradient.stat-neutral: "linear-gradient(135deg, #F5F0EB, #D5C8B8)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F5F0EB, #E8DFD2)"
  gradient.header-accent: "linear-gradient(135deg, rgba(180,83,9,0.1), rgba(180,83,9,0.03))"
  // Badge — Earth
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#F5F0EB"
  badge-neutral-color: "#5E4E3C"
  badge-neutral-border: "#D5C8B8"
  // Progress
  progress-trackBg: "#DDD2C4"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#E8DFD2"
  skeleton-shimmer: "rgba(253,250,247,0.6)"
  grid-borderColor: "#D5C8B8"
  grid-headerBg: "#F5F0EB"
  grid-filterBg: "#F5F0EB"
  grid-filterBorder: "#D5C8B8"
  grid-rowBorder: "#F5F0EB"
  grid-selectedBg: "#EDE5DB"
  scrollbar-color: "#B09E8A #F5F0EB"
}
