@theme sunset {
  palette.primary: orange
  semantic.surface: "#FFF8F1"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#FFF0E1"
  semantic.surface-unread: "#FFF4EB"
  semantic.background: "#FFFCF9"
  semantic.border: "#F5D0B0"
  semantic.border-strong: "#D4956A"
  semantic.text-primary: "#431407"
  semantic.text-secondary: "#78350F"
  semantic.text-tertiary: "#A16207"
  semantic.text-disabled: "#D4B896"
  semantic.text-muted: "#92400E"
  semantic.text-strong: "#3B1106"
  semantic.interactive: "#EA580C"
  semantic.interactive-hover: "#C2410C"
  semantic.interactive-active: "#9A3412"
  semantic.focus-ring: "#FDBA74"
  semantic.info-bg: "#FFF7ED"
  semantic.destructive: "#DC2626"
  semantic.destructive-hover: "#B91C1C"
  semantic.error: "#DC2626"
  semantic.error-bg: "#FEF2F2"
  semantic.success: "#16A34A"
  semantic.success-light: "#F0FDF4"
  semantic.success-muted: "#BBF7D0"
  semantic.success-text: "#14532D"
  semantic.success-mid: "#15803D"
  semantic.warning: "#D97706"
  semantic.warning-light: "#FFFBEB"
  semantic.warning-muted: "#FDE68A"
  semantic.warning-text: "#713F12"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(234,88,12,.15)"
  // Severity
  severity.info-bg: "#FFF7ED"
  severity.info-color: "#9A3412"
  severity.info-border: "#FDBA74"
  severity.success-bg: "#F0FDF4"
  severity.success-color: "#14532D"
  severity.success-border: "#BBF7D0"
  severity.warning-bg: "#FFFBEB"
  severity.warning-color: "#713F12"
  severity.warning-border: "#FDE68A"
  severity.error-bg: "#FEF2F2"
  severity.error-color: "#991B1B"
  severity.error-border: "#FECACA"

  font.body: "'DM Sans', 'Inter', sans-serif"
  font.heading: "'DM Sans', 'Inter', sans-serif"

  radius.sm: "8px"
  radius.md: "10px"
  radius.lg: "14px"

  borders.default: "1px solid #F5D0B0"
  borders.strong: "1px solid #D4956A"

  elevation.raised: "0 1px 3px rgba(154,52,18,0.08), 0 1px 2px rgba(154,52,18,0.06)"
  elevation.layered: "0 4px 8px rgba(154,52,18,0.08), 0 2px 4px rgba(154,52,18,0.06)"
  elevation.floating: "0 10px 25px rgba(154,52,18,0.12), 0 4px 10px rgba(154,52,18,0.06)"
  elevation.overlay: "0 8px 32px rgba(154,52,18,0.15)"

  // Component tokens
  btn-radius: "10px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#EA580C"
  btn-secondary-border: "#FDBA74"
  btn-secondary-hover: "#FFF7ED"
  btn-ghost-color: "#92400E"
  btn-ghost-hover: "#FFF0E1"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFFFF"
  input-border: "#F5D0B0"
  input-color: "#431407"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "10px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FFFFFF"
  select-border: "#F5D0B0"
  select-radius: "10px"
  modal-radius: "14px"
  modal-shadow: "0 20px 60px rgba(154,52,18,.15)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#F5D0B0"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#F5D0B0"
  // Alert — warm sunset severity
  alert-radius: "10px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "semantic.destructive"
  alert-error-text: "severity.error-color"
  // Stat card gradients — warm sunset tones
  gradient.stat-primary: "linear-gradient(135deg, #FFF7ED, #FDBA74)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #FFF7ED, #FED7AA)"
  gradient.stat-success: "linear-gradient(135deg, #F0FDF4, #BBF7D0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #F0FDF4, #DCFCE7)"
  gradient.stat-warning: "linear-gradient(135deg, #FFFBEB, #FDE68A)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FFFBEB, #FEF3C7)"
  gradient.stat-neutral: "linear-gradient(135deg, #FFF8F1, #F5D0B0)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #FFF8F1, #FAEADB)"
  gradient.header-accent: "linear-gradient(135deg, rgba(234,88,12,0.12), rgba(234,88,12,0.04))"
  // Badge — Sunset
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#FFF8F1"
  badge-neutral-color: "#78350F"
  badge-neutral-border: "#F5D0B0"
  // Progress
  progress-trackBg: "#FAEADB"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#FAEADB"
  skeleton-shimmer: "rgba(255,255,255,0.6)"
  grid-borderColor: "#F5D0B0"
  grid-headerBg: "#FFF8F1"
  grid-filterBg: "#FFF8F1"
  grid-filterBorder: "#F5D0B0"
  grid-rowBorder: "#FFF8F1"
  grid-selectedBg: "#FFF0E1"
  scrollbar-color: "#D4956A #FFF8F1"
}
