@theme pastel {
  palette.primary: purple
  semantic.surface: "#F8F6FF"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#F0ECF8"
  semantic.background: "#FEFEFF"
  semantic.border: "#E0D8F0"
  semantic.border-strong: "#C8BEE0"
  semantic.text-primary: "#2D2642"
  semantic.text-secondary: "#5A5072"
  semantic.text-tertiary: "#8880A0"
  semantic.text-disabled: "#C0B8D0"
  semantic.text-muted: "#706890"
  semantic.text-strong: "#1A1530"
  semantic.interactive: "#9B72CF"
  semantic.interactive-hover: "#8A60BE"
  semantic.interactive-active: "#7850AB"
  semantic.focus-ring: "rgba(155,114,207,0.25)"
  semantic.info-bg: "#F0ECFF"
  semantic.surface-unread: "#F4F0FF"
  semantic.destructive: "#E07088"
  semantic.destructive-hover: "#CC5A72"
  semantic.error: "#CC5A72"
  semantic.error-bg: "#FFF0F3"
  semantic.success: "#6DC090"
  semantic.success-light: "#F0FFF5"
  semantic.success-muted: "#D8F5E4"
  semantic.success-text: "#2A6040"
  semantic.success-mid: "#58B07C"
  semantic.warning: "#E8A848"
  semantic.warning-light: "#FFFAF0"
  semantic.warning-muted: "#FFF0D8"
  semantic.warning-text: "#705020"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(155,114,207,.15)"
  // Severity
  severity.info-bg: "#F0ECFF"
  severity.info-color: "#7858B8"
  severity.info-border: "#D8D0F0"
  severity.success-bg: "#F0FFF5"
  severity.success-color: "#3A8858"
  severity.success-border: "#C0E8D0"
  severity.warning-bg: "#FFFAF0"
  severity.warning-color: "#A07830"
  severity.warning-border: "#F0E0C0"
  severity.error-bg: "#FFF0F3"
  severity.error-color: "#C05068"
  severity.error-border: "#F0D0D8"

  font.body: "'Inter', 'Segoe UI', sans-serif"
  font.heading: "'Inter', 'Segoe UI', sans-serif"

  radius.sm: "8px"
  radius.md: "10px"
  radius.lg: "14px"

  borders.default: "1px solid #E0D8F0"
  borders.strong: "1px solid #C8BEE0"

  elevation.flat: "none"
  elevation.raised: "0 2px 8px rgba(155,114,207,0.08), 0 1px 3px rgba(0,0,0,0.05)"
  elevation.layered: "0 4px 16px rgba(155,114,207,0.1), 0 2px 6px rgba(0,0,0,0.06)"
  elevation.floating: "0 8px 32px rgba(155,114,207,0.12), 0 4px 12px rgba(0,0,0,0.08)"
  elevation.overlay: "0 12px 48px rgba(155,114,207,0.1), 0 0 0 1px rgba(155,114,207,0.08)"
  elevation.inset: "inset 0 2px 4px rgba(0,0,0,0.06)"

  btn-radius: "10px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#5A5072"
  btn-secondary-border: "#D0C8E0"
  btn-secondary-hover: "#F0ECF8"
  btn-ghost-color: "#706890"
  btn-ghost-hover: "#F0ECF8"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFFFF"
  input-border: "#D0C8E0"
  input-color: "#2D2642"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  toggle-trackBg: "#D0C8E0"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#FFFFFF"
  select-border: "#D0C8E0"
  select-bg: "#FFFFFF"
  select-optionHover: "#F0ECF8"
  select-optionSelected: "#F4F0FF"
  modal-backdropBg: "rgba(45,38,66,.3)"
  modal-bg: "#FFFFFF"
  modal-radius: "14px"
  modal-shadow: "0 20px 60px rgba(155,114,207,.15)"
  checkbox-border: "#D0C8E0"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#E0D8F0"
  tab-hoverBg: "rgba(155,114,207,.06)"
  // Alert — Pastel
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Pastel
  gradient.stat-primary: "linear-gradient(135deg, #F0ECFF, #E0D8F0)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F8F6FF, #F0ECFF)"
  gradient.stat-success: "linear-gradient(135deg, #F0FFF5, #D8F5E4)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #F8F6FF, #F0FFF5)"
  gradient.stat-warning: "linear-gradient(135deg, #FFFAF0, #FFF0D8)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #F8F6FF, #FFFAF0)"
  gradient.stat-neutral: "linear-gradient(135deg, #F8F6FF, #F0ECF8)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F8F6FF, #F4F2FA)"
  gradient.header-accent: "linear-gradient(135deg, rgba(155,114,207,0.1), rgba(155,114,207,0.03))"
  // Badge — Pastel
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#F0ECF8"
  badge-neutral-color: "#5A5072"
  badge-neutral-border: "#E0D8F0"
  // Progress
  progress-trackBg: "#E0D8F0"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#F0ECF8"
  skeleton-shimmer: "rgba(155,114,207,0.06)"
  grid-borderColor: "#E0D8F0"
  grid-headerBg: "#F8F6FF"
  grid-filterBg: "#F8F6FF"
  grid-filterBorder: "#D0C8E0"
  grid-rowBorder: "#F0ECF8"
  grid-selectedBg: "#F4F0FF"
  scrollbar-color: "#D0C8E0 #F8F6FF"
}
