@theme monokai {
  palette.primary: pink
  semantic.surface: "#272822"
  semantic.surface-raised: "#2E2F28"
  semantic.surface-hover: "#3E3D32"
  semantic.background: "#1E1F1A"
  semantic.border: "#3E3D32"
  semantic.border-strong: "#5B5A4F"
  semantic.text-primary: "#F8F8F2"
  semantic.text-secondary: "#CFCFC2"
  semantic.text-tertiary: "#75715E"
  semantic.text-disabled: "#49483E"
  semantic.text-muted: "#A6A590"
  semantic.text-strong: "#FFFFFF"
  semantic.interactive: "#F92672"
  semantic.interactive-hover: "#E01E66"
  semantic.interactive-active: "#CC185C"
  semantic.focus-ring: "rgba(249,38,114,0.4)"
  semantic.info-bg: "#2D2A30"
  semantic.surface-unread: "#302E24"
  semantic.destructive: "#F92672"
  semantic.destructive-hover: "#E01E66"
  semantic.error: "#F92672"
  semantic.error-bg: "#3D222A"
  semantic.success: "#A6E22E"
  semantic.success-light: "#252E18"
  semantic.success-muted: "#2E3A1E"
  semantic.success-text: "#A6E22E"
  semantic.success-mid: "#90C826"
  semantic.warning: "#FD971F"
  semantic.warning-light: "#332A18"
  semantic.warning-muted: "#3E3220"
  semantic.warning-text: "#FD971F"
  semantic.on-interactive: "#F8F8F2"
  semantic.on-destructive: "#F8F8F2"
  semantic.focus-ring-shadow: "rgba(249,38,114,.2)"
  // Severity
  severity.info-bg: "#2D2A30"
  severity.info-color: "#66D9EF"
  severity.info-border: "#3E3D32"
  severity.success-bg: "#252E18"
  severity.success-color: "#A6E22E"
  severity.success-border: "#2E3A1E"
  severity.warning-bg: "#332A18"
  severity.warning-color: "#FD971F"
  severity.warning-border: "#3E3220"
  severity.error-bg: "#3D222A"
  severity.error-color: "#F92672"
  severity.error-border: "#502838"

  font.body: "'Fira Code', 'Source Code Pro', monospace"
  font.heading: "'Fira Code', 'Source Code Pro', monospace"

  radius.sm: "4px"
  radius.md: "6px"
  radius.lg: "8px"

  borders.default: "1px solid #3E3D32"
  borders.strong: "1px solid #5B5A4F"

  elevation.flat: "none"
  elevation.raised: "0 2px 6px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.2)"
  elevation.layered: "0 4px 10px rgba(0,0,0,0.3), 0 2px 4px rgba(0,0,0,0.2)"
  elevation.floating: "0 12px 30px rgba(0,0,0,0.4), 0 4px 10px rgba(0,0,0,0.2)"
  elevation.overlay: "0 8px 32px rgba(0,0,0,0.45)"
  elevation.inset: "inset 0 2px 4px rgba(0,0,0,0.3)"

  // Component tokens
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#2E2F28"
  btn-secondary-color: "#F8F8F2"
  btn-secondary-border: "#5B5A4F"
  btn-secondary-hover: "#3E3D32"
  btn-ghost-color: "#CFCFC2"
  btn-ghost-hover: "#3E3D32"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.interactive-active"
  input-bg: "#2E2F28"
  input-border: "#5B5A4F"
  input-color: "#F8F8F2"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  toggle-trackBg: "#3E3D32"
  toggle-trackBgOn: "semantic.success"
  toggle-thumbBg: "#1E1F1A"
  select-border: "#5B5A4F"
  select-bg: "#2E2F28"
  select-optionHover: "#3E3D32"
  select-optionSelected: "#2D2A30"
  modal-backdropBg: "rgba(0,0,0,.6)"
  modal-bg: "#2E2F28"
  modal-shadow: "0 20px 60px rgba(0,0,0,.45)"
  checkbox-border: "#5B5A4F"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#3E3D32"
  tab-hoverBg: "rgba(255,255,255,.05)"
  // Alert — Monokai
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Monokai warm darks
  gradient.stat-primary: "linear-gradient(135deg, #272822, #2D2A30)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #272822, #2A2826)"
  gradient.stat-success: "linear-gradient(135deg, #252E18, #2E3A1E)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #272822, #252E18)"
  gradient.stat-warning: "linear-gradient(135deg, #332A18, #3E3220)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #272822, #332A18)"
  gradient.stat-neutral: "linear-gradient(135deg, #272822, #2E2F28)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #272822, #2A2B24)"
  gradient.header-accent: "linear-gradient(135deg, rgba(249,38,114,0.15), rgba(249,38,114,0.05))"
  // Badge — Monokai
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#2E2F28"
  badge-neutral-color: "#CFCFC2"
  badge-neutral-border: "#3E3D32"
  // Progress
  progress-trackBg: "#3E3D32"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#3E3D32"
  skeleton-shimmer: "rgba(255,255,255,0.06)"
  grid-borderColor: "#3E3D32"
  grid-headerBg: "#272822"
  grid-filterBg: "#272822"
  grid-filterBorder: "#5B5A4F"
  grid-rowBorder: "#2E2F28"
  grid-selectedBg: "#2D2A30"
  scrollbar-color: "#5B5A4F #272822"
}
