@theme sakura {
  palette.primary: rose
  semantic.surface: "#FFF5F5"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#FFE4E8"
  semantic.surface-unread: "#FFF0F3"
  semantic.background: "#FFFBFB"
  semantic.border: "#FECDD3"
  semantic.border-strong: "#FDA4AF"
  semantic.text-primary: "#1C1017"
  semantic.text-secondary: "#6B3A4A"
  semantic.text-tertiary: "#9F6478"
  semantic.text-disabled: "#D4A0B0"
  semantic.text-muted: "#88475E"
  semantic.text-strong: "#150A10"
  semantic.interactive: "#E11D48"
  semantic.interactive-hover: "#BE185D"
  semantic.interactive-active: "#9D174D"
  semantic.focus-ring: "#FCA5C0"
  semantic.info-bg: "#FFF0F3"
  semantic.destructive: "#DC2626"
  semantic.destructive-hover: "#B91C1C"
  semantic.error: "#DC2626"
  semantic.error-bg: "#FEF2F2"
  semantic.success: "#059669"
  semantic.success-light: "#ECFDF5"
  semantic.success-muted: "#A7F3D0"
  semantic.success-text: "#064E3B"
  semantic.success-mid: "#10B981"
  semantic.warning: "#D97706"
  semantic.warning-light: "#FFFBEB"
  semantic.warning-muted: "#FDE68A"
  semantic.warning-text: "#92400E"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(225,29,72,.12)"
  // Severity
  severity.info-bg: "#FFF0F3"
  severity.info-color: "#9D174D"
  severity.info-border: "#FECDD3"
  severity.success-bg: "#ECFDF5"
  severity.success-color: "#064E3B"
  severity.success-border: "#A7F3D0"
  severity.warning-bg: "#FFFBEB"
  severity.warning-color: "#92400E"
  severity.warning-border: "#FDE68A"
  severity.error-bg: "#FEF2F2"
  severity.error-color: "#991B1B"
  severity.error-border: "#FECACA"

  font.body: "'Noto Sans', 'Hiragino Sans', sans-serif"
  font.heading: "'Noto Sans', 'Hiragino Sans', sans-serif"

  radius.sm: "10px"
  radius.md: "12px"
  radius.lg: "16px"

  borders.default: "1px solid #FECDD3"
  borders.strong: "1px solid #FDA4AF"

  elevation.raised: "0 1px 4px rgba(225,29,72,0.06), 0 1px 2px rgba(225,29,72,0.04)"
  elevation.layered: "0 4px 8px rgba(225,29,72,0.06), 0 2px 4px rgba(225,29,72,0.04)"
  elevation.floating: "0 10px 25px rgba(225,29,72,0.1), 0 4px 10px rgba(225,29,72,0.05)"
  elevation.overlay: "0 8px 32px rgba(225,29,72,0.12)"

  // Component tokens
  btn-radius: "12px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#E11D48"
  btn-secondary-border: "#FECDD3"
  btn-secondary-hover: "#FFF0F3"
  btn-ghost-color: "#88475E"
  btn-ghost-hover: "#FFE4E8"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFFFF"
  input-border: "#FECDD3"
  input-color: "#1C1017"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "12px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FFFFFF"
  select-border: "#FECDD3"
  select-radius: "12px"
  modal-radius: "16px"
  modal-shadow: "0 20px 60px rgba(225,29,72,.12)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#FECDD3"
  checkbox-radius: "6px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#FECDD3"
  // Alert — Sakura severity
  alert-radius: "12px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "semantic.destructive"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Sakura soft pinks
  gradient.stat-primary: "linear-gradient(135deg, #FFF0F3, #FECDD3)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #FFF5F5, #FFE4E8)"
  gradient.stat-success: "linear-gradient(135deg, #ECFDF5, #A7F3D0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #ECFDF5, #D1FAE5)"
  gradient.stat-warning: "linear-gradient(135deg, #FFFBEB, #FDE68A)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FFFBEB, #FEF3C7)"
  gradient.stat-neutral: "linear-gradient(135deg, #FFF5F5, #FECDD3)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #FFF5F5, #FFE4E8)"
  gradient.header-accent: "linear-gradient(135deg, rgba(225,29,72,0.08), rgba(225,29,72,0.03))"
  // Badge — Sakura
  badge-borderWidth: "1px"
  badge-radius: "10px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#FFF5F5"
  badge-neutral-color: "#6B3A4A"
  badge-neutral-border: "#FECDD3"
  // Progress
  progress-trackBg: "#FFE4E8"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#FFE4E8"
  skeleton-shimmer: "rgba(255,255,255,0.6)"
  grid-borderColor: "#FECDD3"
  grid-headerBg: "#FFF5F5"
  grid-filterBg: "#FFF5F5"
  grid-filterBorder: "#FECDD3"
  grid-rowBorder: "#FFF5F5"
  grid-selectedBg: "#FFF0F3"
  scrollbar-color: "#FDA4AF #FFF5F5"
}
