@theme geek {
  palette.primary: green
  semantic.surface: "#0a0a0a"
  semantic.surface-raised: "#111111"
  semantic.surface-hover: "#1a1a1a"
  semantic.background: "#000000"
  semantic.border: "#00ff41"
  semantic.border-strong: "#00ff41"
  semantic.text-primary: "#00ff41"
  semantic.text-secondary: "#00cc33"
  semantic.text-tertiary: "#009926"
  semantic.text-muted: "#00b33c"
  semantic.text-disabled: "#004d1a"
  semantic.interactive: "#00ff41"
  semantic.interactive-hover: "#33ff6b"
  semantic.interactive-active: "#00cc33"
  semantic.focus-ring: "#00ff4140"
  semantic.info-bg: "#0a1a0a"
  semantic.error-bg: "#1a0a0a"
  semantic.error: "#ff0040"
  semantic.destructive: "#ff0040"
  semantic.destructive-hover: "#cc0033"
  semantic.success: "#00ff41"
  semantic.success-light: "#0a1a0a"
  semantic.success-muted: "#003311"
  semantic.success-text: "#00ff41"
  semantic.success-mid: "#00cc33"
  semantic.warning: "#ffff00"
  semantic.warning-light: "#1a1a00"
  semantic.warning-muted: "#333300"
  semantic.warning-text: "#ffff00"
  semantic.text-strong: "#00ff41"
  semantic.on-interactive: "#000000"
  semantic.on-destructive: "#000000"
  semantic.focus-ring-shadow: "rgba(0,255,65,.2)"
  // Severity
  severity.info-bg: "#0a1a0a"
  severity.info-color: "#00ff41"
  severity.info-border: "#00ff41"
  severity.success-bg: "#0a1a0a"
  severity.success-color: "#00ff41"
  severity.success-border: "#00ff41"
  severity.warning-bg: "#1a1a00"
  severity.warning-color: "#ffff00"
  severity.warning-border: "#ffff00"
  severity.error-bg: "#1a0a0a"
  severity.error-color: "#ff0040"
  severity.error-border: "#ff0040"

  font.body: "'Fira Code', 'Consolas', 'Monaco', monospace"
  font.heading: "'Fira Code', 'Consolas', 'Monaco', monospace"
  font.mono: "'Fira Code', 'Consolas', 'Monaco', monospace"

  borders.default: "1px solid #00ff41"
  borders.strong: "1px solid #33ff6b"

  radius.sm: "2px"
  radius.md: "4px"
  radius.lg: "6px"

  elevation.raised: "0 0 10px rgba(0,255,65,0.3), 0 0 0 1px rgba(0,255,65,0.4)"
  elevation.layered: "0 0 20px rgba(0,255,65,0.25), 0 0 0 1px rgba(0,255,65,0.4)"
  elevation.floating: "0 0 40px rgba(0,255,65,0.3), 0 0 0 1px rgba(0,255,65,0.4)"

  btn-radius: "2px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#0a0a0a"
  btn-secondary-color: "#00ff41"
  btn-secondary-border: "#00ff41"
  btn-secondary-hover: "#111111"
  btn-ghost-color: "#00ff41"
  btn-ghost-hover: "#111111"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  btn-fontWeight: "400"
  btn-textTransform: "uppercase"
  btn-letterSpacing: "0.1em"
  input-bg: "#0a0a0a"
  input-border: "#00ff41"
  input-color: "#00ff41"
  input-radius: "2px"
  input-focusBorder: "semantic.interactive-hover"
  input-focusRing: "semantic.focus-ring-shadow"
  select-bg: "#0a0a0a"
  select-border: "#00ff41"
  select-radius: "2px"
  select-optionHover: "#111111"
  select-optionSelected: "#003311"
  toggle-trackBg: "#1a1a1a"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#000000"
  toggle-radius: "2px"
  modal-backdropBg: "rgba(0,0,0,.8)"
  modal-bg: "#0a0a0a"
  modal-radius: "4px"
  modal-shadow: "0 0 30px rgba(0,255,65,0.3), 0 0 0 1px #00ff41"
  btn-shadow: "0 0 8px rgba(0,255,65,0.3), inset 0 0 4px rgba(0,255,65,0.1)"
  input-shadow: "0 0 8px rgba(0,255,65,0.25), inset 0 0 4px rgba(0,255,65,0.05)"
  checkbox-border: "#00ff41"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-radius: "2px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#00ff41"
  tab-hoverBg: "#111111"
  badge-radius: "2px"
  badge-fontSize: "11px"
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#111111"
  badge-neutral-color: "#00cc33"
  badge-neutral-border: "#00ff41"
  // Stat card gradients — geek: dark with subtle glow
  gradient.stat-primary: "linear-gradient(135deg, #0a1a0a, #003311)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #0a0a0a, #001a0a)"
  gradient.stat-success: "linear-gradient(135deg, #0a1a0a, #003311)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #0a0a0a, #001a0a)"
  gradient.stat-warning: "linear-gradient(135deg, #1a1a00, #333300)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #0a0a0a, #1a1a00)"
  gradient.stat-neutral: "linear-gradient(135deg, #0a0a0a, #111111)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #0a0a0a, #0f0f0f)"
  gradient.header-accent: "linear-gradient(135deg, rgba(0,255,65,0.15), rgba(0,255,65,0.05))"
  progress-trackBg: "#1a1a1a"
  progress-fillBg: "semantic.interactive"
  // Alert — geek: green glow severity
  alert-radius: "2px"
  alert-shadow: "0 0 8px rgba(0,255,65,0.2)"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Scrollbar
  // Skeleton + Grid (matrix green)
  skeleton-bg: "#1a1a1a"
  skeleton-shimmer: "rgba(0,255,65,0.1)"
  grid-borderColor: "#00ff41"
  grid-headerBg: "#0a0a0a"
  grid-filterBg: "#0a0a0a"
  grid-filterBorder: "#00ff41"
  grid-rowBorder: "#111111"
  grid-selectedBg: "#003311"
  scrollbar-color: "#00ff41 #0a0a0a"
}
