@theme newspaper {
  palette.primary: slate
  semantic.surface: "#F5F1EB"
  semantic.surface-raised: "#FFFEF9"
  semantic.surface-hover: "#EDE8E0"
  semantic.surface-unread: "#F8F4EE"
  semantic.background: "#FFFEF9"
  semantic.border: "#D8D0C4"
  semantic.border-strong: "#B8AE9E"
  semantic.text-primary: "#1A1A1A"
  semantic.text-secondary: "#4A4A4A"
  semantic.text-tertiary: "#7A7A7A"
  semantic.text-disabled: "#B0B0B0"
  semantic.text-muted: "#5E5E5E"
  semantic.text-strong: "#000000"
  semantic.interactive: "#8B0000"
  semantic.interactive-hover: "#6B0000"
  semantic.interactive-active: "#500000"
  semantic.focus-ring: "#D4A0A0"
  semantic.info-bg: "#F0ECE6"
  semantic.destructive: "#CC0000"
  semantic.destructive-hover: "#A00000"
  semantic.error: "#CC0000"
  semantic.error-bg: "#FCE8E8"
  semantic.success: "#2E6B30"
  semantic.success-light: "#EBF5EB"
  semantic.success-muted: "#C0DCC0"
  semantic.success-text: "#1A4420"
  semantic.success-mid: "#246828"
  semantic.warning: "#9E6B00"
  semantic.warning-light: "#FDF6E0"
  semantic.warning-muted: "#F0DCA0"
  semantic.warning-text: "#6E4A00"
  semantic.on-interactive: "#FFFEF9"
  semantic.on-destructive: "#FFFEF9"
  semantic.focus-ring-shadow: "rgba(139,0,0,.1)"
  // Severity
  severity.info-bg: "#F0ECE6"
  severity.info-color: "#8B0000"
  severity.info-border: "#D8D0C4"
  severity.success-bg: "#EBF5EB"
  severity.success-color: "#1A4420"
  severity.success-border: "#C0DCC0"
  severity.warning-bg: "#FDF6E0"
  severity.warning-color: "#6E4A00"
  severity.warning-border: "#E8D290"
  severity.error-bg: "#FCE8E8"
  severity.error-color: "#CC0000"
  severity.error-border: "#E8B0B0"

  font.body: "'Georgia', 'Times New Roman', 'Palatino', serif"
  font.heading: "'Playfair Display', 'Georgia', 'Times New Roman', serif"

  radius.sm: "2px"
  radius.md: "3px"
  radius.lg: "4px"

  borders.default: "1px solid #D8D0C4"
  borders.strong: "1px solid #B8AE9E"

  elevation.raised: "0 1px 2px rgba(0,0,0,0.06)"
  elevation.layered: "0 2px 4px rgba(0,0,0,0.06)"
  elevation.floating: "0 4px 12px rgba(0,0,0,0.08)"
  elevation.overlay: "0 6px 20px rgba(0,0,0,0.1)"

  btn-radius: "3px"
  btn-fontWeight: "600"
  btn-letterSpacing: "0.02em"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFEF9"
  btn-secondary-color: "#8B0000"
  btn-secondary-border: "#8B0000"
  btn-secondary-hover: "#F5F1EB"
  btn-ghost-color: "#4A4A4A"
  btn-ghost-hover: "#EDE8E0"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFEF9"
  input-border: "#D8D0C4"
  input-color: "#1A1A1A"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "3px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FFFEF9"
  select-border: "#D8D0C4"
  select-radius: "3px"
  modal-radius: "4px"
  modal-shadow: "0 10px 40px rgba(0,0,0,.1)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#B8AE9E"
  checkbox-radius: "2px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#D8D0C4"
  // Alert — Newspaper
  alert-radius: "3px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "#1A1A1A"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "#1A1A1A"
  // Stat card gradients — Newspaper muted
  gradient.stat-primary: "linear-gradient(135deg, #F0ECE6, #D8D0C4)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F5F1EB, #EDE8E0)"
  gradient.stat-success: "linear-gradient(135deg, #EBF5EB, #C0DCC0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #EBF5EB, #D8ECD8)"
  gradient.stat-warning: "linear-gradient(135deg, #FDF6E0, #F0DCA0)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FDF6E0, #F6EAC0)"
  gradient.stat-neutral: "linear-gradient(135deg, #F5F1EB, #D8D0C4)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F5F1EB, #EDE8E0)"
  gradient.header-accent: "linear-gradient(135deg, rgba(139,0,0,0.06), rgba(139,0,0,0.02))"
  // Badge — Newspaper
  badge-borderWidth: "1px"
  badge-radius: "2px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#F5F1EB"
  badge-neutral-color: "#4A4A4A"
  badge-neutral-border: "#D8D0C4"
  // Progress
  progress-trackBg: "#DDD6CA"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#E8E0D6"
  skeleton-shimmer: "rgba(255,254,249,0.6)"
  grid-borderColor: "#D8D0C4"
  grid-headerBg: "#F5F1EB"
  grid-filterBg: "#F5F1EB"
  grid-filterBorder: "#D8D0C4"
  grid-rowBorder: "#F5F1EB"
  grid-selectedBg: "#EDE8E0"
  scrollbar-color: "#B8AE9E #F5F1EB"
}
