@theme mui {
  palette.primary: blue
  semantic.interactive: "#1976d2"
  semantic.interactive-hover: "#1565c0"
  semantic.interactive-active: "#0d47a1"
  semantic.focus-ring: "#90caf9"
  semantic.on-interactive: "#ffffff"
  semantic.on-destructive: "#ffffff"
  semantic.focus-ring-shadow: "rgba(25,118,210,.12)"
  // Severity
  severity.info-bg: "#e3f2fd"
  severity.info-color: "#1565c0"
  severity.info-border: "#90caf9"
  severity.success-bg: "#e8f5e9"
  severity.success-color: "#2e7d32"
  severity.success-border: "#a5d6a7"
  severity.warning-bg: "#fff3e0"
  severity.warning-color: "#e65100"
  severity.warning-border: "#ffcc80"
  severity.error-bg: "#fbe9e7"
  severity.error-color: "#c62828"
  severity.error-border: "#ef9a9a"

  font.body: "'Roboto', 'Helvetica Neue', sans-serif"
  font.heading: "'Roboto', 'Helvetica Neue', sans-serif"

  borders.default: "1px solid #e0e0e0"
  borders.strong: "1px solid #bdbdbd"

  radius.sm: "4px"
  radius.md: "4px"
  radius.lg: "8px"

  elevation.raised: "0 2px 1px -1px rgba(0,0,0,.2), 0 1px 1px rgba(0,0,0,.14), 0 1px 3px rgba(0,0,0,.12)"
  elevation.layered: "0 3px 3px -2px rgba(0,0,0,.2), 0 3px 4px rgba(0,0,0,.14), 0 1px 8px rgba(0,0,0,.12)"
  elevation.floating: "0 5px 5px -3px rgba(0,0,0,.2), 0 8px 10px 1px rgba(0,0,0,.14), 0 3px 14px 2px rgba(0,0,0,.12)"

  btn-primary-bg: "semantic.interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-radius: "4px"
  btn-textTransform: "uppercase"
  btn-letterSpacing: "0.05em"
  btn-fontWeight: "500"
  btn-secondary-bg: "transparent"
  btn-secondary-color: "#1976d2"
  btn-secondary-border: "#1976d2"
  btn-secondary-hover: "rgba(25,118,210,.04)"
  input-radius: "4px"
  input-bg: "#f5f5f5"
  input-border: "#bdbdbd"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  select-radius: "4px"
  select-border: "#bdbdbd"
  select-bg: "#f5f5f5"
  modal-radius: "4px"
  tab-activeColor: "semantic.interactive"
  checkbox-checkedBg: "semantic.interactive"
  toggle-trackBgOn: "semantic.interactive"
  // Badge — MUI
  badge-borderWidth: "0"
  badge-radius: "4px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#f5f5f5"
  badge-neutral-color: "#616161"
  badge-neutral-border: "#e0e0e0"
  // Alert — MUI severity colors
  alert-radius: "4px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "#0d47a1"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "#1b5e20"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "#ed6c02"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "#d32f2f"
  alert-error-text: "#b71c1c"
  // Stat card gradients — MUI palette
  gradient.stat-primary: "linear-gradient(135deg, #e3f2fd, #90caf9)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #e3f2fd, #bbdefb)"
  gradient.stat-success: "linear-gradient(135deg, #e8f5e9, #a5d6a7)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #e8f5e9, #c8e6c9)"
  gradient.stat-warning: "linear-gradient(135deg, #fff3e0, #ffcc80)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #fff3e0, #ffe0b2)"
  gradient.stat-neutral: "linear-gradient(135deg, #f5f5f5, #e0e0e0)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #f5f5f5, #eeeeee)"
  gradient.header-accent: "linear-gradient(135deg, rgba(25,118,210,0.1), rgba(25,118,210,0.03))"
  // Grid
  grid-borderColor: "#e0e0e0"
  grid-headerBg: "#fafafa"
  grid-filterBg: "#f5f5f5"
  grid-filterBorder: "#e0e0e0"
  grid-rowBorder: "#f5f5f5"
  grid-selectedBg: "#e3f2fd"
  // Progress
  progress-trackBg: "#e0e0e0"
  progress-fillBg: "semantic.interactive"
  // Scrollbar
  scrollbar-color: "#bdbdbd #f5f5f5"
}
