@theme catppuccin {
  palette.primary: purple
  semantic.surface: "#1E1E2E"
  semantic.surface-raised: "#313244"
  semantic.surface-hover: "#45475A"
  semantic.background: "#181825"
  semantic.border: "#45475A"
  semantic.border-strong: "#585B70"
  semantic.text-primary: "#CDD6F4"
  semantic.text-secondary: "#BAC2DE"
  semantic.text-tertiary: "#A6ADC8"
  semantic.text-disabled: "#585B70"
  semantic.text-muted: "#9399B2"
  semantic.text-strong: "#FFFFFF"
  semantic.interactive: "#CBA6F7"
  semantic.interactive-hover: "#B48EE0"
  semantic.interactive-active: "#9D76C9"
  semantic.focus-ring: "rgba(203,166,247,0.4)"
  semantic.info-bg: "#1E1E30"
  semantic.surface-unread: "#262638"
  semantic.destructive: "#F38BA8"
  semantic.destructive-hover: "#E06B8C"
  semantic.error: "#F38BA8"
  semantic.error-bg: "#302028"
  semantic.success: "#A6E3A1"
  semantic.success-light: "#1E2E1E"
  semantic.success-muted: "#283828"
  semantic.success-text: "#A6E3A1"
  semantic.success-mid: "#8AD688"
  semantic.warning: "#F9E2AF"
  semantic.warning-light: "#2E2C20"
  semantic.warning-muted: "#3A3828"
  semantic.warning-text: "#F9E2AF"
  semantic.on-interactive: "#1E1E2E"
  semantic.on-destructive: "#1E1E2E"
  semantic.focus-ring-shadow: "rgba(203,166,247,.2)"
  // Severity
  severity.info-bg: "#1E1E30"
  severity.info-color: "#89B4FA"
  severity.info-border: "#45475A"
  severity.success-bg: "#1E2E1E"
  severity.success-color: "#A6E3A1"
  severity.success-border: "#283828"
  severity.warning-bg: "#2E2C20"
  severity.warning-color: "#F9E2AF"
  severity.warning-border: "#3A3828"
  severity.error-bg: "#302028"
  severity.error-color: "#F38BA8"
  severity.error-border: "#402830"

  font.body: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"
  font.heading: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"

  radius.sm: "8px"
  radius.md: "10px"
  radius.lg: "14px"

  borders.default: "1px solid #45475A"
  borders.strong: "1px solid #585B70"

  elevation.flat: "none"
  elevation.raised: "0 2px 6px rgba(0,0,0,0.25), 0 1px 2px rgba(0,0,0,0.18)"
  elevation.layered: "0 4px 10px rgba(0,0,0,0.25), 0 2px 4px rgba(0,0,0,0.18)"
  elevation.floating: "0 12px 30px rgba(0,0,0,0.35), 0 4px 10px rgba(0,0,0,0.18)"
  elevation.overlay: "0 8px 32px rgba(0,0,0,0.4)"
  elevation.inset: "inset 0 2px 4px rgba(0,0,0,0.25)"

  btn-radius: "10px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#313244"
  btn-secondary-color: "#CDD6F4"
  btn-secondary-border: "#585B70"
  btn-secondary-hover: "#45475A"
  btn-ghost-color: "#BAC2DE"
  btn-ghost-hover: "#45475A"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#313244"
  input-border: "#585B70"
  input-color: "#CDD6F4"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "10px"
  toggle-trackBg: "#45475A"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#1E1E2E"
  select-border: "#585B70"
  select-bg: "#313244"
  select-radius: "10px"
  select-optionHover: "#45475A"
  select-optionSelected: "#262638"
  modal-backdropBg: "rgba(0,0,0,.55)"
  modal-bg: "#313244"
  modal-radius: "14px"
  modal-shadow: "0 20px 60px rgba(0,0,0,.4)"
  checkbox-border: "#585B70"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#45475A"
  tab-hoverBg: "rgba(255,255,255,.05)"
  // Alert — Catppuccin
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Catppuccin pastels
  gradient.stat-primary: "linear-gradient(135deg, #1E1E2E, #262638)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #1E1E2E, #222232)"
  gradient.stat-success: "linear-gradient(135deg, #1E2E1E, #283828)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #1E1E2E, #1E2E1E)"
  gradient.stat-warning: "linear-gradient(135deg, #2E2C20, #3A3828)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #1E1E2E, #2E2C20)"
  gradient.stat-neutral: "linear-gradient(135deg, #1E1E2E, #313244)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #1E1E2E, #272738)"
  gradient.header-accent: "linear-gradient(135deg, rgba(203,166,247,0.15), rgba(203,166,247,0.05))"
  // Badge — Catppuccin
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#313244"
  badge-neutral-color: "#BAC2DE"
  badge-neutral-border: "#45475A"
  // Progress
  progress-trackBg: "#45475A"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#45475A"
  skeleton-shimmer: "rgba(255,255,255,0.06)"
  grid-borderColor: "#45475A"
  grid-headerBg: "#1E1E2E"
  grid-filterBg: "#1E1E2E"
  grid-filterBorder: "#585B70"
  grid-rowBorder: "#313244"
  grid-selectedBg: "#262638"
  scrollbar-color: "#585B70 #1E1E2E"
}
