@theme lavender {
  palette.primary: violet
  semantic.surface: "#F5F3FF"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#EDE9FE"
  semantic.surface-unread: "#F3F0FF"
  semantic.background: "#FAFAFE"
  semantic.border: "#DDD6FE"
  semantic.border-strong: "#C4B5FD"
  semantic.text-primary: "#1E1033"
  semantic.text-secondary: "#5B4784"
  semantic.text-tertiary: "#8B7AAF"
  semantic.text-disabled: "#C4B5E0"
  semantic.text-muted: "#6D5B99"
  semantic.text-strong: "#150A28"
  semantic.interactive: "#7C3AED"
  semantic.interactive-hover: "#6D28D9"
  semantic.interactive-active: "#5B21B6"
  semantic.focus-ring: "#C4B5FD"
  semantic.info-bg: "#F3F0FF"
  semantic.destructive: "#DC2626"
  semantic.destructive-hover: "#B91C1C"
  semantic.error: "#DC2626"
  semantic.error-bg: "#FEF2F2"
  semantic.success: "#059669"
  semantic.success-light: "#ECFDF5"
  semantic.success-muted: "#A7F3D0"
  semantic.success-text: "#064E3B"
  semantic.success-mid: "#10B981"
  semantic.warning: "#D97706"
  semantic.warning-light: "#FFFBEB"
  semantic.warning-muted: "#FDE68A"
  semantic.warning-text: "#92400E"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(124,58,237,.12)"
  // Severity
  severity.info-bg: "#F3F0FF"
  severity.info-color: "#5B21B6"
  severity.info-border: "#DDD6FE"
  severity.success-bg: "#ECFDF5"
  severity.success-color: "#064E3B"
  severity.success-border: "#A7F3D0"
  severity.warning-bg: "#FFFBEB"
  severity.warning-color: "#92400E"
  severity.warning-border: "#FDE68A"
  severity.error-bg: "#FEF2F2"
  severity.error-color: "#991B1B"
  severity.error-border: "#FECACA"

  font.body: "'DM Sans', 'Inter', sans-serif"
  font.heading: "'DM Sans', 'Inter', sans-serif"

  radius.sm: "10px"
  radius.md: "12px"
  radius.lg: "16px"

  borders.default: "1px solid #DDD6FE"
  borders.strong: "1px solid #C4B5FD"

  elevation.raised: "0 1px 4px rgba(124,58,237,0.06), 0 1px 2px rgba(124,58,237,0.04)"
  elevation.layered: "0 4px 8px rgba(124,58,237,0.06), 0 2px 4px rgba(124,58,237,0.04)"
  elevation.floating: "0 10px 25px rgba(124,58,237,0.1), 0 4px 10px rgba(124,58,237,0.05)"
  elevation.overlay: "0 8px 32px rgba(124,58,237,0.12)"

  // Component tokens
  btn-radius: "12px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#7C3AED"
  btn-secondary-border: "#DDD6FE"
  btn-secondary-hover: "#F5F3FF"
  btn-ghost-color: "#6D5B99"
  btn-ghost-hover: "#EDE9FE"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFFFF"
  input-border: "#DDD6FE"
  input-color: "#1E1033"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "12px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FFFFFF"
  select-border: "#DDD6FE"
  select-radius: "12px"
  modal-radius: "16px"
  modal-shadow: "0 20px 60px rgba(124,58,237,.12)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#DDD6FE"
  checkbox-radius: "6px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#DDD6FE"
  // Alert — Lavender severity
  alert-radius: "12px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "semantic.destructive"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Lavender soft purples
  gradient.stat-primary: "linear-gradient(135deg, #F3F0FF, #DDD6FE)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F5F3FF, #EDE9FE)"
  gradient.stat-success: "linear-gradient(135deg, #ECFDF5, #A7F3D0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #ECFDF5, #D1FAE5)"
  gradient.stat-warning: "linear-gradient(135deg, #FFFBEB, #FDE68A)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FFFBEB, #FEF3C7)"
  gradient.stat-neutral: "linear-gradient(135deg, #F5F3FF, #DDD6FE)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F5F3FF, #EDE9FE)"
  gradient.header-accent: "linear-gradient(135deg, rgba(124,58,237,0.08), rgba(124,58,237,0.03))"
  // Badge — Lavender
  badge-borderWidth: "1px"
  badge-radius: "10px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#F5F3FF"
  badge-neutral-color: "#5B4784"
  badge-neutral-border: "#DDD6FE"
  // Progress
  progress-trackBg: "#EDE9FE"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#EDE9FE"
  skeleton-shimmer: "rgba(255,255,255,0.6)"
  grid-borderColor: "#DDD6FE"
  grid-headerBg: "#F5F3FF"
  grid-filterBg: "#F5F3FF"
  grid-filterBorder: "#DDD6FE"
  grid-rowBorder: "#F5F3FF"
  grid-selectedBg: "#F3F0FF"
  scrollbar-color: "#C4B5FD #F5F3FF"
}
