@theme bootstrap {
  palette.primary: blue
  semantic.interactive: "#0d6efd"
  semantic.interactive-hover: "#0b5ed7"
  semantic.interactive-active: "#0a58ca"
  semantic.focus-ring: "#b6d4fe"
  semantic.destructive: "#dc3545"
  semantic.destructive-hover: "#b02a37"
  semantic.success: "#198754"
  semantic.warning: "#ffc107"
  semantic.on-interactive: "#fff"
  semantic.on-destructive: "#fff"
  semantic.focus-ring-shadow: "rgba(13,110,253,.25)"
  // Severity
  severity.info-bg: "#cfe2ff"
  severity.info-color: "#052c65"
  severity.info-border: "#9ec5fe"
  severity.success-bg: "#d1e7dd"
  severity.success-color: "#0a3622"
  severity.success-border: "#a3cfbb"
  severity.warning-bg: "#fff3cd"
  severity.warning-color: "#664d03"
  severity.warning-border: "#ffe69c"
  severity.error-bg: "#f8d7da"
  severity.error-color: "#58151c"
  severity.error-border: "#f1aeb5"

  borders.default: "1px solid #dee2e6"
  borders.strong: "1px solid #adb5bd"

  radius.sm: "4px"
  radius.md: "6px"
  radius.lg: "8px"

  btn-radius: "6px"
  btn-fontWeight: "400"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#6c757d"
  btn-secondary-color: "#fff"
  btn-secondary-border: "#6c757d"
  btn-secondary-hover: "#5c636a"
  btn-ghost-color: "#0d6efd"
  btn-ghost-hover: "rgba(13,110,253,.1)"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-radius: "6px"
  input-focusBorder: "#86b7fe"
  input-focusRing: "semantic.focus-ring-shadow"
  select-radius: "6px"
  toggle-trackBgOn: "semantic.interactive"
  modal-radius: "8px"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  // Badge — Bootstrap
  badge-borderWidth: "0"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#e2e3e5"
  badge-neutral-color: "#41464b"
  badge-neutral-border: "#d3d6d8"
  // Alert — Bootstrap severity colors
  alert-radius: "6px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "#9ec5fe"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "#a3cfbb"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "#ffe69c"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "#f1aeb5"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Bootstrap palette
  gradient.stat-primary: "linear-gradient(135deg, #cfe2ff, #9ec5fe)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #e7f1ff, #cfe2ff)"
  gradient.stat-success: "linear-gradient(135deg, #d1e7dd, #a3cfbb)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #e8f5ee, #d1e7dd)"
  gradient.stat-warning: "linear-gradient(135deg, #fff3cd, #ffe69c)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #fff9e6, #fff3cd)"
  gradient.stat-neutral: "linear-gradient(135deg, #e2e3e5, #ced4da)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #f8f9fa, #e2e3e5)"
  gradient.header-accent: "linear-gradient(135deg, rgba(13,110,253,0.1), rgba(13,110,253,0.03))"
  // Grid
  grid-borderColor: "#dee2e6"
  grid-headerBg: "#f8f9fa"
  grid-filterBg: "#f8f9fa"
  grid-filterBorder: "#dee2e6"
  grid-rowBorder: "#f8f9fa"
  grid-selectedBg: "#cfe2ff"
  // Progress
  progress-trackBg: "#dee2e6"
  progress-fillBg: "semantic.interactive"
  // Scrollbar
  scrollbar-color: "#adb5bd #f8f9fa"
}
