@theme cartoon {
  palette.primary: emerald
  semantic.interactive: "#2d6a4f"
  semantic.interactive-hover: "#1b4332"
  semantic.interactive-active: "#081c15"
  semantic.focus-ring: "#95d5b2"
  semantic.surface: "#fdf6ec"
  semantic.surface-raised: "#fffdf7"
  semantic.surface-hover: "#f5ead4"
  semantic.background: "#fefcf6"
  semantic.border: "#d4a574"
  semantic.border-strong: "#b07d50"
  semantic.text-primary: "#2d1b0e"
  semantic.text-secondary: "#5c3d1f"
  semantic.on-interactive: "#fffdf7"
  semantic.on-destructive: "#fffdf7"
  semantic.focus-ring-shadow: "rgba(45,106,79,.15)"
  // Severity
  severity.info-bg: "#e6f7ff"
  severity.info-color: "#2d6a4f"
  severity.info-border: "#2d6a4f"
  severity.success-bg: "#f0fff4"
  severity.success-color: "#2d6a4f"
  severity.success-border: "#2d6a4f"
  severity.warning-bg: "#fff8e1"
  severity.warning-color: "#5c3d1f"
  severity.warning-border: "#d4a574"
  severity.error-bg: "#fff0f0"
  severity.error-color: "#e76f51"
  severity.error-border: "#e76f51"

  borders.default: "2px solid #d4a574"
  borders.strong: "2px solid #b07d50"

  font.body: "'Nunito', 'Comic Sans MS', cursive, sans-serif"
  font.heading: "'Nunito', 'Comic Sans MS', cursive, sans-serif"

  spacing.1: "5px"
  spacing.2: "10px"
  spacing.3: "15px"
  spacing.4: "20px"
  spacing.5: "25px"
  spacing.6: "30px"
  spacing.8: "40px"
  spacing.10: "50px"

  radius.sm: "14px"
  radius.md: "18px"
  radius.lg: "24px"

  elevation.raised: "4px 4px 0 rgba(45,27,14,0.15)"
  elevation.layered: "6px 6px 0 rgba(45,27,14,0.12)"
  elevation.floating: "8px 8px 0 rgba(45,27,14,0.1)"

  btn-radius: "20px"
  btn-borderWidth: "2px"
  btn-fontWeight: "700"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#fffdf7"
  btn-secondary-color: "#2d6a4f"
  btn-secondary-border: "#2d6a4f"
  btn-secondary-hover: "#f5ead4"
  btn-ghost-color: "#5c3d1f"
  btn-ghost-hover: "#f5ead4"
  btn-destructive-bg: "#e76f51"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "#c1553e"
  input-radius: "14px"
  input-borderWidth: "2px"
  input-bg: "#fffdf7"
  input-border: "#d4a574"
  input-color: "#2d1b0e"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  select-radius: "14px"
  select-bg: "#fffdf7"
  select-border: "#d4a574"
  toggle-radius: "999px"
  toggle-trackBgOn: "semantic.interactive"
  modal-radius: "24px"
  modal-shadow: "8px 8px 0 rgba(45,27,14,0.1)"
  checkbox-radius: "8px"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#d4a574"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#d4a574"
  badge-radius: "20px"
  badge-borderWidth: "2px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#f5ead4"
  badge-neutral-color: "#5c3d1f"
  badge-neutral-border: "#d4a574"
  borderWidth-default: "2px"
  // Alert — warm cartoon severity colors + thick borders
  alert-radius: "18px"
  alert-borderWidth: "2px"
  alert-shadow: "4px 4px 0 rgba(45,27,14,0.15)"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "#2d1b0e"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "#2d1b0e"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "#d4a574"
  alert-warning-text: "#2d1b0e"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "#2d1b0e"
  // Stat card gradients — warm cartoon tones
  gradient.stat-primary: "linear-gradient(135deg, #e6f7ef, #a7d7c5)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #f0fff4, #c5e8d6)"
  gradient.stat-success: "linear-gradient(135deg, #e6f7ef, #a7d7c5)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #f0fff4, #c5e8d6)"
  gradient.stat-warning: "linear-gradient(135deg, #fff8e1, #f0d4a0)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #fffbee, #f5e0bb)"
  gradient.stat-neutral: "linear-gradient(135deg, #fdf6ec, #e8d5b8)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #fdf6ec, #f0e0cc)"
  gradient.header-accent: "linear-gradient(135deg, rgba(45,106,79,0.15), rgba(45,106,79,0.05))"
  // Progress
  progress-trackBg: "#e8d5b8"
  progress-fillBg: "semantic.interactive"
  // Scrollbar
  // Skeleton + Grid (warm)
  skeleton-bg: "#e8d5b8"
  skeleton-shimmer: "rgba(255,255,255,0.5)"
  grid-borderColor: "#d4a574"
  grid-filterBg: "#f5ead4"
  grid-filterBorder: "#d4a574"
  grid-rowBorder: "#f5ead4"
  grid-selectedBg: "#d4e7d0"
  scrollbar-color: "#d4a574 #fdf6ec"
}
