@theme nord {
  palette.primary: blue
  semantic.surface: "#2E3440"
  semantic.surface-raised: "#3B4252"
  semantic.surface-hover: "#434C5E"
  semantic.background: "#242933"
  semantic.border: "#4C566A"
  semantic.border-strong: "#616E88"
  semantic.text-primary: "#ECEFF4"
  semantic.text-secondary: "#D8DEE9"
  semantic.text-tertiary: "#9DA7B8"
  semantic.text-disabled: "#616E88"
  semantic.text-muted: "#B4BCC8"
  semantic.text-strong: "#E5E9F0"
  semantic.interactive: "#88C0D0"
  semantic.interactive-hover: "#8FBCBB"
  semantic.interactive-active: "#5E81AC"
  semantic.focus-ring: "rgba(136,192,208,0.4)"
  semantic.info-bg: "#2E3440"
  semantic.surface-unread: "#2E3A4A"
  semantic.destructive: "#BF616A"
  semantic.destructive-hover: "#A5444D"
  semantic.error: "#BF616A"
  semantic.error-bg: "#3B2D30"
  semantic.success: "#A3BE8C"
  semantic.success-light: "#2D3328"
  semantic.success-muted: "#3A4432"
  semantic.success-text: "#A3BE8C"
  semantic.success-mid: "#8FAD78"
  semantic.warning: "#EBCB8B"
  semantic.warning-light: "#3B3524"
  semantic.warning-muted: "#4A4230"
  semantic.warning-text: "#EBCB8B"
  semantic.on-interactive: "#2E3440"
  semantic.on-destructive: "#ECEFF4"
  semantic.focus-ring-shadow: "rgba(136,192,208,.2)"
  // Severity
  severity.info-bg: "#2E3A4A"
  severity.info-color: "#88C0D0"
  severity.info-border: "#5E81AC"
  severity.success-bg: "#2D3328"
  severity.success-color: "#A3BE8C"
  severity.success-border: "#3A4432"
  severity.warning-bg: "#3B3524"
  severity.warning-color: "#EBCB8B"
  severity.warning-border: "#4A4230"
  severity.error-bg: "#3B2D30"
  severity.error-color: "#BF616A"
  severity.error-border: "#5A3338"

  font.body: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"
  font.heading: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"

  radius.sm: "6px"
  radius.md: "8px"
  radius.lg: "12px"

  borders.default: "1px solid #4C566A"
  borders.strong: "1px solid #616E88"

  elevation.flat: "none"
  elevation.raised: "0 1px 4px rgba(0,0,0,0.25), 0 1px 2px rgba(0,0,0,0.2)"
  elevation.layered: "0 4px 8px rgba(0,0,0,0.25), 0 2px 4px rgba(0,0,0,0.2)"
  elevation.floating: "0 10px 30px rgba(0,0,0,0.35), 0 4px 10px rgba(0,0,0,0.2)"
  elevation.overlay: "0 8px 32px rgba(0,0,0,0.4)"
  elevation.inset: "inset 0 2px 4px rgba(0,0,0,0.25)"

  // Component tokens
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "#81A1C1"
  btn-secondary-bg: "#3B4252"
  btn-secondary-color: "#D8DEE9"
  btn-secondary-border: "#4C566A"
  btn-secondary-hover: "#434C5E"
  btn-ghost-color: "#D8DEE9"
  btn-ghost-hover: "#434C5E"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#3B4252"
  input-border: "#4C566A"
  input-color: "#ECEFF4"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  toggle-trackBg: "#4C566A"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#2E3440"
  select-border: "#4C566A"
  select-bg: "#3B4252"
  select-optionHover: "#434C5E"
  select-optionSelected: "#2E3A4A"
  modal-backdropBg: "rgba(0,0,0,.5)"
  modal-bg: "#3B4252"
  modal-shadow: "0 20px 60px rgba(0,0,0,.4)"
  checkbox-border: "#4C566A"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#4C566A"
  tab-hoverBg: "rgba(255,255,255,.05)"
  // Alert — Nord severity
  alert-info-bg: "#2E3440"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Nord muted tones
  gradient.stat-primary: "linear-gradient(135deg, #2E3440, #2E3A4A)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #2E3440, #323A48)"
  gradient.stat-success: "linear-gradient(135deg, #2D3328, #3A4432)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #2E3440, #2D3328)"
  gradient.stat-warning: "linear-gradient(135deg, #3B3524, #4A4230)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #2E3440, #3B3524)"
  gradient.stat-neutral: "linear-gradient(135deg, #2E3440, #3B4252)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #2E3440, #353C4A)"
  gradient.header-accent: "linear-gradient(135deg, rgba(136,192,208,0.15), rgba(136,192,208,0.05))"
  // Badge — Nord
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#3B4252"
  badge-neutral-color: "#D8DEE9"
  badge-neutral-border: "#4C566A"
  // Progress
  progress-trackBg: "#434C5E"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#434C5E"
  skeleton-shimmer: "rgba(255,255,255,0.06)"
  grid-borderColor: "#4C566A"
  grid-headerBg: "#2E3440"
  grid-filterBg: "#2E3440"
  grid-filterBorder: "#4C566A"
  grid-rowBorder: "#3B4252"
  grid-selectedBg: "#2E3A4A"
  scrollbar-color: "#4C566A #2E3440"
}
