@theme illustration {
  palette.primary: green
  semantic.interactive: "#52c41a"
  semantic.interactive-hover: "#389e0d"
  semantic.interactive-active: "#237804"
  semantic.focus-ring: "#b7eb8f"
  semantic.surface: "#fff9f0"
  semantic.surface-raised: "#ffffff"
  semantic.surface-hover: "#fff0e6"
  semantic.background: "#fff9f0"
  semantic.border: "#2c2c2c"
  semantic.border-strong: "#2c2c2c"
  semantic.text-primary: "#2c2c2c"
  semantic.text-secondary: "#595959"
  semantic.on-interactive: "#ffffff"
  semantic.on-destructive: "#ffffff"
  // Severity
  severity.info-bg: "#e6f7ff"
  severity.info-color: "#2c2c2c"
  severity.info-border: "#2c2c2c"
  severity.success-bg: "#f6ffed"
  severity.success-color: "#2c2c2c"
  severity.success-border: "#2c2c2c"
  severity.warning-bg: "#fffbe6"
  severity.warning-color: "#2c2c2c"
  severity.warning-border: "#2c2c2c"
  severity.error-bg: "#fff2f0"
  severity.error-color: "#2c2c2c"
  severity.error-border: "#2c2c2c"

  borders.default: "3px solid #2c2c2c"
  borders.strong: "3px solid #2c2c2c"

  radius.sm: "8px"
  radius.md: "12px"
  radius.lg: "16px"

  elevation.raised: "4px 4px 0 #2c2c2c"
  elevation.layered: "4px 4px 0 #2c2c2c"
  elevation.floating: "4px 4px 0 #2c2c2c"
  elevation.overlay: "4px 4px 0 #2c2c2c"

  btn-radius: "12px"
  btn-borderWidth: "3px"
  btn-fontWeight: "600"
  btn-textTransform: "uppercase"
  btn-letterSpacing: "0.5px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#ffffff"
  btn-secondary-color: "#2c2c2c"
  btn-secondary-border: "#2c2c2c"
  btn-secondary-hover: "#fff0e6"
  btn-ghost-color: "#2c2c2c"
  btn-ghost-hover: "#fff0e6"
  btn-destructive-bg: "#fa5252"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "#e03131"
  btn-shadow: "4px 4px 0 #2c2c2c"
  input-borderWidth: "3px"
  input-border: "#2c2c2c"
  input-radius: "12px"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "none"
  input-shadow: "4px 4px 0 #2c2c2c"
  select-border: "#2c2c2c"
  select-radius: "12px"
  toggle-trackBgOn: "semantic.interactive"
  toggle-radius: "12px"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#2c2c2c"
  checkbox-radius: "4px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#2c2c2c"
  badge-radius: "12px"
  badge-borderWidth: "3px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#f0f0f0"
  badge-neutral-color: "#2c2c2c"
  badge-neutral-border: "#2c2c2c"
  borderWidth-default: "3px"
  modal-radius: "16px"
  modal-shadow: "4px 4px 0 #2c2c2c"
  progress-trackBg: "#e8e8e8"
  progress-fillBg: "semantic.interactive"
  // Alert — illustration: thick dark borders + hard offset shadow
  alert-radius: "12px"
  alert-borderWidth: "3px"
  alert-shadow: "4px 4px 0 #2c2c2c"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — illustration green/warm tones
  gradient.stat-primary: "linear-gradient(135deg, #f6ffed, #b7eb8f)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #f6ffed, #d9f7be)"
  gradient.stat-success: "linear-gradient(135deg, #f6ffed, #b7eb8f)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #f6ffed, #d9f7be)"
  gradient.stat-warning: "linear-gradient(135deg, #fffbe6, #ffe58f)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #fffbe6, #fff1b8)"
  gradient.stat-neutral: "linear-gradient(135deg, #fff9f0, #e8d8c0)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #fff9f0, #f0e4d0)"
  gradient.header-accent: "linear-gradient(135deg, rgba(82,196,26,0.15), rgba(82,196,26,0.05))"
  // Scrollbar
  // Skeleton + Grid (illustration style)
  skeleton-bg: "#e8e8e8"
  skeleton-shimmer: "rgba(255,255,255,0.5)"
  grid-borderColor: "#2c2c2c"
  grid-filterBg: "#fff0e6"
  grid-filterBorder: "#2c2c2c"
  grid-rowBorder: "#e8e8e8"
  grid-selectedBg: "#d4f0c0"
  scrollbar-color: "#2c2c2c #fff9f0"
}
