@theme high-contrast {
  palette.primary: blue
  semantic.surface: "#FFFFFF"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#E8E8E8"
  semantic.background: "#FFFFFF"
  semantic.border: "#000000"
  semantic.border-strong: "#000000"
  semantic.text-primary: "#000000"
  semantic.text-secondary: "#1A1A1A"
  semantic.text-tertiary: "#333333"
  semantic.text-disabled: "#767676"
  semantic.text-muted: "#2A2A2A"
  semantic.text-strong: "#000000"
  semantic.interactive: "#0050D8"
  semantic.interactive-hover: "#003CA0"
  semantic.interactive-active: "#002A70"
  semantic.focus-ring: "rgba(0,80,216,0.5)"
  semantic.info-bg: "#E0EEFF"
  semantic.surface-unread: "#E8F0FF"
  semantic.destructive: "#CC0000"
  semantic.destructive-hover: "#A00000"
  semantic.error: "#CC0000"
  semantic.error-bg: "#FFE0E0"
  semantic.success: "#006600"
  semantic.success-light: "#E0FFE0"
  semantic.success-muted: "#C0F0C0"
  semantic.success-text: "#004400"
  semantic.success-mid: "#005500"
  semantic.warning: "#885500"
  semantic.warning-light: "#FFF5E0"
  semantic.warning-muted: "#FFE8C0"
  semantic.warning-text: "#664400"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(0,80,216,.3)"
  // Severity
  severity.info-bg: "#E0EEFF"
  severity.info-color: "#003088"
  severity.info-border: "#0050D8"
  severity.success-bg: "#E0FFE0"
  severity.success-color: "#004400"
  severity.success-border: "#006600"
  severity.warning-bg: "#FFF5E0"
  severity.warning-color: "#664400"
  severity.warning-border: "#885500"
  severity.error-bg: "#FFE0E0"
  severity.error-color: "#880000"
  severity.error-border: "#CC0000"

  font.body: "'Inter', 'Segoe UI', sans-serif"
  font.heading: "'Inter', 'Segoe UI', sans-serif"

  radius.sm: "4px"
  radius.md: "6px"
  radius.lg: "8px"

  borders.default: "2px solid #000000"
  borders.strong: "3px solid #000000"

  elevation.flat: "none"
  elevation.raised: "0 0 0 2px #000000"
  elevation.layered: "0 0 0 2px #000000"
  elevation.floating: "0 0 0 3px #000000"
  elevation.overlay: "0 0 0 3px #000000"
  elevation.inset: "inset 0 0 0 2px #000000"

  btn-radius: "6px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#000000"
  btn-secondary-border: "#000000"
  btn-secondary-hover: "#E8E8E8"
  btn-ghost-color: "#000000"
  btn-ghost-hover: "#E8E8E8"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FFFFFF"
  input-border: "#000000"
  input-color: "#000000"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  toggle-trackBg: "#767676"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#FFFFFF"
  select-border: "#000000"
  select-bg: "#FFFFFF"
  select-optionHover: "#E8E8E8"
  select-optionSelected: "#E0EEFF"
  modal-backdropBg: "rgba(0,0,0,.5)"
  modal-bg: "#FFFFFF"
  modal-radius: "6px"
  modal-shadow: "0 0 0 3px #000000"
  checkbox-border: "#000000"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#000000"
  tab-hoverBg: "#E8E8E8"
  // Alert — High-Contrast
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — High-Contrast
  gradient.stat-primary: "linear-gradient(135deg, #E0EEFF, #C0DDFF)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #FFFFFF, #E0EEFF)"
  gradient.stat-success: "linear-gradient(135deg, #E0FFE0, #C0F0C0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #FFFFFF, #E0FFE0)"
  gradient.stat-warning: "linear-gradient(135deg, #FFF5E0, #FFE8C0)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FFFFFF, #FFF5E0)"
  gradient.stat-neutral: "linear-gradient(135deg, #F0F0F0, #E0E0E0)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #FFFFFF, #F0F0F0)"
  gradient.header-accent: "linear-gradient(135deg, rgba(0,80,216,0.08), rgba(0,80,216,0.02))"
  // Badge — High-Contrast
  badge-borderWidth: "2px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#F0F0F0"
  badge-neutral-color: "#000000"
  badge-neutral-border: "#000000"
  // Progress
  progress-trackBg: "#E0E0E0"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#E8E8E8"
  skeleton-shimmer: "rgba(0,0,0,0.04)"
  grid-borderColor: "#000000"
  grid-headerBg: "#F0F0F0"
  grid-filterBg: "#F0F0F0"
  grid-filterBorder: "#000000"
  grid-rowBorder: "#E0E0E0"
  grid-selectedBg: "#E0EEFF"
  scrollbar-color: "#767676 #FFFFFF"
}
