@theme shadcn {
  palette.primary: zinc
  palette.neutral: zinc
  semantic.interactive: "#18181b"
  semantic.interactive-hover: "#27272a"
  semantic.interactive-active: "#09090b"
  semantic.focus-ring: "#a1a1aa"
  semantic.surface: "#fafafa"
  semantic.surface-raised: "#ffffff"
  semantic.surface-hover: "#f4f4f5"
  semantic.border: "#e4e4e7"
  semantic.border-strong: "#a1a1aa"
  semantic.text-primary: "#09090b"
  semantic.text-secondary: "#71717a"
  semantic.on-interactive: "#fafafa"
  semantic.on-destructive: "#ffffff"
  // Severity
  severity.info-bg: "#f4f4f5"
  severity.info-color: "#18181b"
  severity.info-border: "#e4e4e7"
  severity.success-bg: "#f0fdf4"
  severity.success-color: "#18181b"
  severity.success-border: "#e4e4e7"
  severity.warning-bg: "#fffbeb"
  severity.warning-color: "#18181b"
  severity.warning-border: "#e4e4e7"
  severity.error-bg: "#fef2f2"
  severity.error-color: "#ef4444"
  severity.error-border: "#e4e4e7"

  borders.default: "1px solid #e4e4e7"
  borders.strong: "1px solid #a1a1aa"

  radius.sm: "6px"
  radius.md: "6px"
  radius.lg: "8px"

  elevation.raised: "0 1px 2px rgba(0,0,0,0.05)"
  elevation.layered: "0 1px 3px rgba(0,0,0,0.08)"
  elevation.floating: "0 4px 12px rgba(0,0,0,0.08)"

  btn-radius: "6px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#ffffff"
  btn-secondary-color: "#18181b"
  btn-secondary-border: "#e4e4e7"
  btn-secondary-hover: "#f4f4f5"
  btn-ghost-color: "#71717a"
  btn-ghost-hover: "#f4f4f5"
  btn-destructive-bg: "#ef4444"
  btn-destructive-hover: "#dc2626"
  input-radius: "6px"
  input-bg: "#f4f4f5"
  input-border: "#e4e4e7"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "none"
  select-radius: "6px"
  select-bg: "#f4f4f5"
  select-border: "#e4e4e7"
  toggle-radius: "6px"
  toggle-trackBgOn: "semantic.interactive"
  modal-radius: "8px"
  modal-shadow: "0 4px 16px rgba(0,0,0,0.1)"
  checkbox-radius: "4px"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#e4e4e7"
  badge-radius: "6px"
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#f4f4f5"
  badge-neutral-color: "#71717a"
  badge-neutral-border: "#e4e4e7"
  // Alert — shadcn minimal
  alert-radius: "6px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "semantic.interactive"
  // Stat card gradients — shadcn minimal
  gradient.stat-primary: "linear-gradient(135deg, #f4f4f5, #e4e4e7)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #fafafa, #f4f4f5)"
  gradient.stat-success: "linear-gradient(135deg, #f0fdf4, #dcfce7)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #f0fdf4, #e8fbe8)"
  gradient.stat-warning: "linear-gradient(135deg, #fffbeb, #fef3c7)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #fffbeb, #fef9c3)"
  gradient.stat-neutral: "linear-gradient(135deg, #f4f4f5, #e4e4e7)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #fafafa, #f4f4f5)"
  gradient.header-accent: "linear-gradient(135deg, rgba(24,24,27,0.05), rgba(24,24,27,0.02))"
  // Grid
  grid-borderColor: "#e4e4e7"
  grid-headerBg: "#fafafa"
  grid-filterBg: "#f4f4f5"
  grid-filterBorder: "#e4e4e7"
  grid-rowBorder: "#f4f4f5"
  grid-selectedBg: "#f4f4f5"
  // Progress
  progress-trackBg: "#e4e4e7"
  progress-fillBg: "semantic.interactive"
  // Scrollbar
  scrollbar-color: "#d4d4d8 transparent"
}
