@theme solarized {
  palette.primary: cyan
  semantic.surface: "#EEE8D5"
  semantic.surface-raised: "#FDF6E3"
  semantic.surface-hover: "#E8E0CC"
  semantic.surface-unread: "#F5EDDA"
  semantic.background: "#FDF6E3"
  semantic.border: "#D3CBB7"
  semantic.border-strong: "#93A1A1"
  semantic.text-primary: "#073642"
  semantic.text-secondary: "#586E75"
  semantic.text-tertiary: "#657B83"
  semantic.text-disabled: "#93A1A1"
  semantic.text-muted: "#586E75"
  semantic.text-strong: "#002B36"
  semantic.interactive: "#2AA198"
  semantic.interactive-hover: "#238E86"
  semantic.interactive-active: "#1C7A74"
  semantic.focus-ring: "#8ACCC7"
  semantic.info-bg: "#EEF5F4"
  semantic.destructive: "#DC322F"
  semantic.destructive-hover: "#C42825"
  semantic.error: "#DC322F"
  semantic.error-bg: "#FCEDEC"
  semantic.success: "#859900"
  semantic.success-light: "#F4F7E6"
  semantic.success-muted: "#E0E8B8"
  semantic.success-text: "#4A5600"
  semantic.success-mid: "#6F8200"
  semantic.warning: "#B58900"
  semantic.warning-light: "#FAF4E0"
  semantic.warning-muted: "#F0E2A8"
  semantic.warning-text: "#7A5C00"
  semantic.on-interactive: "#FDF6E3"
  semantic.on-destructive: "#FDF6E3"
  semantic.focus-ring-shadow: "rgba(42,161,152,.15)"
  // Severity
  severity.info-bg: "#EEF5F4"
  severity.info-color: "#1C7A74"
  severity.info-border: "#8ACCC7"
  severity.success-bg: "#F4F7E6"
  severity.success-color: "#4A5600"
  severity.success-border: "#B8CC4C"
  severity.warning-bg: "#FAF4E0"
  severity.warning-color: "#7A5C00"
  severity.warning-border: "#D4B24C"
  severity.error-bg: "#FCEDEC"
  severity.error-color: "#DC322F"
  severity.error-border: "#E8918F"

  font.body: "'Source Sans 3', 'Source Sans Pro', 'Helvetica Neue', sans-serif"
  font.heading: "'Source Sans 3', 'Source Sans Pro', 'Helvetica Neue', sans-serif"

  radius.sm: "4px"
  radius.md: "6px"
  radius.lg: "8px"

  borders.default: "1px solid #D3CBB7"
  borders.strong: "1px solid #93A1A1"

  elevation.raised: "0 1px 3px rgba(0,43,54,0.08), 0 1px 2px rgba(0,43,54,0.06)"
  elevation.layered: "0 4px 6px rgba(0,43,54,0.08), 0 2px 4px rgba(0,43,54,0.06)"
  elevation.floating: "0 10px 25px rgba(0,43,54,0.1), 0 4px 10px rgba(0,43,54,0.05)"
  elevation.overlay: "0 8px 32px rgba(0,43,54,0.12)"

  // Component tokens
  btn-radius: "6px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FDF6E3"
  btn-secondary-color: "#2AA198"
  btn-secondary-border: "#93A1A1"
  btn-secondary-hover: "#EEE8D5"
  btn-ghost-color: "#586E75"
  btn-ghost-hover: "#EEE8D5"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#FDF6E3"
  input-border: "#D3CBB7"
  input-color: "#073642"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  input-radius: "6px"
  toggle-trackBgOn: "semantic.interactive"
  select-bg: "#FDF6E3"
  select-border: "#D3CBB7"
  select-radius: "6px"
  modal-radius: "8px"
  modal-shadow: "0 20px 60px rgba(0,43,54,.15)"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-border: "#93A1A1"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#D3CBB7"
  // Alert — Solarized
  alert-radius: "6px"
  alert-info-bg: "severity.info-bg"
  alert-info-border: "semantic.interactive"
  alert-info-text: "#073642"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "semantic.success"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "semantic.warning"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "#073642"
  // Stat card gradients — Solarized warm tans
  gradient.stat-primary: "linear-gradient(135deg, #EEF5F4, #C4E3E0)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F0F5F4, #DAEAE8)"
  gradient.stat-success: "linear-gradient(135deg, #F4F7E6, #E0E8B8)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #F4F7E6, #EAEFCE)"
  gradient.stat-warning: "linear-gradient(135deg, #FAF4E0, #F0E2A8)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FAF4E0, #F5EBC4)"
  gradient.stat-neutral: "linear-gradient(135deg, #EEE8D5, #D3CBB7)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F5F0E0, #EEE8D5)"
  gradient.header-accent: "linear-gradient(135deg, rgba(42,161,152,0.1), rgba(42,161,152,0.03))"
  // Badge — Solarized
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#EEE8D5"
  badge-neutral-color: "#586E75"
  badge-neutral-border: "#D3CBB7"
  // Progress
  progress-trackBg: "#D3CBB7"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#E2DCCA"
  skeleton-shimmer: "rgba(253,246,227,0.6)"
  grid-borderColor: "#D3CBB7"
  grid-headerBg: "#EEE8D5"
  grid-filterBg: "#EEE8D5"
  grid-filterBorder: "#D3CBB7"
  grid-rowBorder: "#EEE8D5"
  grid-selectedBg: "#E8E0CC"
  scrollbar-color: "#93A1A1 #EEE8D5"
}
