@theme brutalist {
  palette.primary: slate
  semantic.surface: "#FFFFFF"
  semantic.surface-raised: "#FFFFFF"
  semantic.surface-hover: "#F0F0F0"
  semantic.surface-unread: "#F5F5F5"
  semantic.background: "#FFFFFF"
  semantic.border: "#000000"
  semantic.border-strong: "#000000"
  semantic.text-primary: "#000000"
  semantic.text-secondary: "#333333"
  semantic.text-tertiary: "#666666"
  semantic.text-disabled: "#999999"
  semantic.text-muted: "#555555"
  semantic.text-strong: "#000000"
  semantic.interactive: "#000000"
  semantic.interactive-hover: "#333333"
  semantic.interactive-active: "#000000"
  semantic.focus-ring: "#000000"
  semantic.info-bg: "#F0F0F0"
  semantic.destructive: "#FF0000"
  semantic.destructive-hover: "#CC0000"
  semantic.error: "#FF0000"
  semantic.error-bg: "#FFE0E0"
  semantic.success: "#008000"
  semantic.success-light: "#E0FFE0"
  semantic.success-muted: "#C0F0C0"
  semantic.success-text: "#004000"
  semantic.success-mid: "#006600"
  semantic.warning: "#FF8800"
  semantic.warning-light: "#FFF0D0"
  semantic.warning-muted: "#FFE0A0"
  semantic.warning-text: "#664400"
  semantic.on-interactive: "#FFFFFF"
  semantic.on-destructive: "#FFFFFF"
  // Severity
  severity.info-bg: "#FFFFFF"
  severity.info-color: "#000000"
  severity.info-border: "#000000"
  severity.success-bg: "#FFFFFF"
  severity.success-color: "#008000"
  severity.success-border: "#000000"
  severity.warning-bg: "#FFFFFF"
  severity.warning-color: "#FF8800"
  severity.warning-border: "#000000"
  severity.error-bg: "#FFFFFF"
  severity.error-color: "#FF0000"
  severity.error-border: "#000000"

  font.body: "'system-ui', 'Arial', sans-serif"
  font.heading: "'system-ui', 'Arial', sans-serif"

  radius.sm: "0px"
  radius.md: "0px"
  radius.lg: "0px"

  borders.default: "3px solid #000000"
  borders.strong: "3px solid #000000"

  elevation.flat: "none"
  elevation.raised: "none"
  elevation.layered: "none"
  elevation.floating: "6px 6px 0 #000000"
  elevation.overlay: "8px 8px 0 #000000"
  elevation.inset: "none"

  // Component tokens
  btn-radius: "0px"
  btn-borderWidth: "3px"
  btn-fontWeight: "700"
  btn-textTransform: "uppercase"
  btn-letterSpacing: "0.05em"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#FFFFFF"
  btn-secondary-color: "#000000"
  btn-secondary-border: "#000000"
  btn-secondary-hover: "#F0F0F0"
  btn-ghost-color: "#000000"
  btn-ghost-hover: "#F0F0F0"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  btn-shadow: "4px 4px 0 #000000"
  input-bg: "#FFFFFF"
  input-border: "#000000"
  input-borderWidth: "3px"
  input-color: "#000000"
  input-radius: "0px"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "none"
  input-shadow: "4px 4px 0 #000000"
  select-bg: "#FFFFFF"
  select-border: "#000000"
  select-radius: "0px"
  toggle-trackBgOn: "semantic.interactive"
  toggle-radius: "0px"
  modal-radius: "0px"
  modal-shadow: "8px 8px 0 #000000"
  checkbox-border: "#000000"
  checkbox-checkedBg: "semantic.interactive"
  checkbox-radius: "0px"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#000000"
  borderWidth-default: "3px"
  // Alert — Brutalist stark
  alert-radius: "0px"
  alert-borderWidth: "3px"
  alert-shadow: "4px 4px 0 #000000"
  alert-info-bg: "#F0F0F0"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "#E0FFE0"
  alert-success-border: "#000000"
  alert-success-text: "semantic.interactive"
  alert-warning-bg: "#FFF0D0"
  alert-warning-border: "#000000"
  alert-warning-text: "semantic.interactive"
  alert-error-bg: "#FFE0E0"
  alert-error-border: "severity.error-color"
  alert-error-text: "semantic.interactive"
  // Stat card gradients — Brutalist: flat, no gradients (solid fills)
  gradient.stat-primary: "linear-gradient(135deg, #F0F0F0, #E0E0E0)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #F5F5F5, #F0F0F0)"
  gradient.stat-success: "linear-gradient(135deg, #E0FFE0, #C0F0C0)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #F0FFF0, #E0FFE0)"
  gradient.stat-warning: "linear-gradient(135deg, #FFF0D0, #FFE0A0)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #FFF8E0, #FFF0D0)"
  gradient.stat-neutral: "linear-gradient(135deg, #F0F0F0, #E0E0E0)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #F5F5F5, #F0F0F0)"
  gradient.header-accent: "linear-gradient(135deg, rgba(0,0,0,0.05), rgba(0,0,0,0.02))"
  // Badge — Brutalist
  badge-radius: "0px"
  badge-borderWidth: "3px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#FFFFFF"
  badge-neutral-color: "#333333"
  badge-neutral-border: "#000000"
  // Progress
  progress-trackBg: "#E0E0E0"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#E0E0E0"
  skeleton-shimmer: "rgba(255,255,255,0.5)"
  grid-borderColor: "#000000"
  grid-headerBg: "#F0F0F0"
  grid-filterBg: "#F0F0F0"
  grid-filterBorder: "#000000"
  grid-rowBorder: "#E0E0E0"
  grid-selectedBg: "#F0F0F0"
  scrollbar-color: "#000000 #FFFFFF"
}
