@theme cobalt {
  palette.primary: blue
  semantic.surface: "#15232D"
  semantic.surface-raised: "#1A2D3A"
  semantic.surface-hover: "#203848"
  semantic.background: "#0F1C25"
  semantic.border: "#1E4263"
  semantic.border-strong: "#2A5A80"
  semantic.text-primary: "#E1EFFF"
  semantic.text-secondary: "#B0CDE8"
  semantic.text-tertiary: "#6A90B0"
  semantic.text-disabled: "#2A5A80"
  semantic.text-muted: "#8AAFCC"
  semantic.text-strong: "#FFFFFF"
  semantic.interactive: "#FFC600"
  semantic.interactive-hover: "#E0B000"
  semantic.interactive-active: "#C89A00"
  semantic.focus-ring: "rgba(255,198,0,0.4)"
  semantic.info-bg: "#182838"
  semantic.surface-unread: "#1C3040"
  semantic.destructive: "#FF5F56"
  semantic.destructive-hover: "#E04840"
  semantic.error: "#FF5F56"
  semantic.error-bg: "#2E1C1A"
  semantic.success: "#3DD68C"
  semantic.success-light: "#142A22"
  semantic.success-muted: "#1A3830"
  semantic.success-text: "#3DD68C"
  semantic.success-mid: "#30C078"
  semantic.warning: "#FFB020"
  semantic.warning-light: "#2E2810"
  semantic.warning-muted: "#3E3418"
  semantic.warning-text: "#FFB020"
  semantic.on-interactive: "#0F1C25"
  semantic.on-destructive: "#FFFFFF"
  semantic.focus-ring-shadow: "rgba(255,198,0,.2)"
  // Severity
  severity.info-bg: "#182838"
  severity.info-color: "#5EC4FF"
  severity.info-border: "#1E4263"
  severity.success-bg: "#142A22"
  severity.success-color: "#3DD68C"
  severity.success-border: "#1A3830"
  severity.warning-bg: "#2E2810"
  severity.warning-color: "#FFB020"
  severity.warning-border: "#3E3418"
  severity.error-bg: "#2E1C1A"
  severity.error-color: "#FF5F56"
  severity.error-border: "#482828"

  font.body: "'Inter', 'Segoe UI', sans-serif"
  font.heading: "'Inter', 'Segoe UI', sans-serif"

  radius.sm: "6px"
  radius.md: "8px"
  radius.lg: "12px"

  borders.default: "1px solid #1E4263"
  borders.strong: "1px solid #2A5A80"

  elevation.flat: "none"
  elevation.raised: "0 2px 6px rgba(0,0,0,0.3), 0 1px 2px rgba(0,0,0,0.2)"
  elevation.layered: "0 4px 10px rgba(0,0,0,0.3), 0 2px 4px rgba(0,0,0,0.2)"
  elevation.floating: "0 12px 30px rgba(0,0,0,0.4), 0 4px 10px rgba(0,0,0,0.2)"
  elevation.overlay: "0 8px 32px rgba(0,0,0,0.45)"
  elevation.inset: "inset 0 2px 4px rgba(0,0,0,0.3)"

  btn-radius: "8px"
  btn-primary-bg: "semantic.interactive"
  btn-primary-color: "semantic.on-interactive"
  btn-primary-hover: "semantic.interactive-hover"
  btn-secondary-bg: "#1A2D3A"
  btn-secondary-color: "#E1EFFF"
  btn-secondary-border: "#2A5A80"
  btn-secondary-hover: "#203848"
  btn-ghost-color: "#B0CDE8"
  btn-ghost-hover: "#203848"
  btn-destructive-bg: "semantic.destructive"
  btn-destructive-color: "semantic.on-destructive"
  btn-destructive-hover: "semantic.destructive-hover"
  input-bg: "#1A2D3A"
  input-border: "#2A5A80"
  input-color: "#E1EFFF"
  input-focusBorder: "semantic.interactive"
  input-focusRing: "semantic.focus-ring-shadow"
  toggle-trackBg: "#1E4263"
  toggle-trackBgOn: "semantic.interactive"
  toggle-thumbBg: "#0F1C25"
  select-border: "#2A5A80"
  select-bg: "#1A2D3A"
  select-optionHover: "#203848"
  select-optionSelected: "#1C3040"
  modal-backdropBg: "rgba(0,0,0,.6)"
  modal-bg: "#1A2D3A"
  modal-radius: "12px"
  modal-shadow: "0 20px 60px rgba(0,0,0,.45)"
  checkbox-border: "#2A5A80"
  checkbox-checkedBg: "semantic.interactive"
  tab-activeColor: "semantic.interactive"
  tab-borderColor: "#1E4263"
  tab-hoverBg: "rgba(255,255,255,.05)"
  // Alert — Cobalt
  alert-info-bg: "severity.info-bg"
  alert-info-border: "severity.info-color"
  alert-info-text: "severity.info-color"
  alert-success-bg: "severity.success-bg"
  alert-success-border: "severity.success-color"
  alert-success-text: "severity.success-color"
  alert-warning-bg: "severity.warning-bg"
  alert-warning-border: "severity.warning-color"
  alert-warning-text: "severity.warning-color"
  alert-error-bg: "severity.error-bg"
  alert-error-border: "severity.error-color"
  alert-error-text: "severity.error-color"
  // Stat card gradients — Cobalt
  gradient.stat-primary: "linear-gradient(135deg, #15232D, #1C3040)"
  gradient.stat-primary-subtle: "linear-gradient(135deg, #15232D, #182838)"
  gradient.stat-success: "linear-gradient(135deg, #142A22, #1A3830)"
  gradient.stat-success-subtle: "linear-gradient(135deg, #15232D, #142A22)"
  gradient.stat-warning: "linear-gradient(135deg, #2E2810, #3E3418)"
  gradient.stat-warning-subtle: "linear-gradient(135deg, #15232D, #2E2810)"
  gradient.stat-neutral: "linear-gradient(135deg, #15232D, #1A2D3A)"
  gradient.stat-neutral-subtle: "linear-gradient(135deg, #15232D, #182530)"
  gradient.header-accent: "linear-gradient(135deg, rgba(255,198,0,0.15), rgba(94,196,255,0.08))"
  // Badge — Cobalt
  badge-borderWidth: "1px"
  badge-info-bg: "severity.info-bg"
  badge-info-color: "severity.info-color"
  badge-info-border: "severity.info-border"
  badge-success-bg: "severity.success-bg"
  badge-success-color: "severity.success-color"
  badge-success-border: "severity.success-border"
  badge-warning-bg: "severity.warning-bg"
  badge-warning-color: "severity.warning-color"
  badge-warning-border: "severity.warning-border"
  badge-error-bg: "severity.error-bg"
  badge-error-color: "severity.error-color"
  badge-error-border: "severity.error-border"
  badge-neutral-bg: "#1A2D3A"
  badge-neutral-color: "#B0CDE8"
  badge-neutral-border: "#1E4263"
  // Progress
  progress-trackBg: "#1E4263"
  progress-fillBg: "semantic.interactive"
  // Skeleton + Grid
  skeleton-bg: "#203848"
  skeleton-shimmer: "rgba(255,198,0,0.06)"
  grid-borderColor: "#1E4263"
  grid-headerBg: "#15232D"
  grid-filterBg: "#15232D"
  grid-filterBorder: "#2A5A80"
  grid-rowBorder: "#1A2D3A"
  grid-selectedBg: "#1C3040"
  scrollbar-color: "#2A5A80 #15232D"
}
